WebApplicationFinal/Models/Good.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.GoodOrders = new HashSet<GoodOrder>();
            this.ImportDetails = new HashSet<ImportDetail>();
        }
    
        public string GID { get; set; }
        public string GName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Manufacture { get; set; }
        public Nullable<int> ImportPrice { get; set; }
        public Nullable<int> SellingPrice { get; set; }
        public byte[] GPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodOrder> GoodOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportDetail> ImportDetails { get; set; }
    }
}

WebApplicationFinal/Controllers/GoodOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationFinal.Models;

namespace WebApplicationFinal.Controllers
{
    public class GoodOrdersController : Controller
    {
        private FinalSE db = new FinalSE();

        public ActionResult Create(string id)
        {
            Good good = db.Goods.Find(id);
            ViewBag.Price = good.SellingPrice;
            ViewBag.Quantity = good.Quantity;
            ViewBag.GName = good.GName;
            ViewBag.AID = new SelectList(db.Agents, "AID", "AName");
            ViewBag.GID = new SelectList(db.Goods, "GID", "GName", good.GID);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OID,AID,GID,Quantity,OrderDate,TotalPrice,PaymentMethod")] GoodOrder goodOrder)
        {
            if (ModelState.IsValid)
            {
                db.GoodOrders.Add(goodOrder);
                db.SaveChanges();

                Good good = db.Goods.Find(goodOrder.GID);
                good.Quantity = good.Quantity - goodOrder.Quantity;
                db.Entry(good).State = EntityState.Modified;
                db.SaveChanges();

                Random random = new Random();
                char letter = (char)('A' + random.Next(0, 26));
                string deliveryID = "D" + letter + DateTime.Now.ToString("mmss");
                Delivery delivery = new Delivery();
                delivery.DeliveryID = deliveryID;
                delivery.OID = goodOrder.OID;
                delivery.AID = goodOrder.AID;
                delivery.PaymentStatus = "Paid";
                delivery.GoodsStatus = "Pending";

                db.Deliveries.Add(delivery);
                db.SaveChanges();

                return RedirectToAction("Index", "Deliveries");
            }

            ViewBag.AID = new SelectList(db.Agents, "AID", "AName", goodOrder.AID);
            ViewBag.GID = new SelectList(db.Goods, "GID", "GName", goodOrder.GID);
            return View(goodOrder);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationFinal/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationFinal.Models;

namespace WebApplicationFinal.Controllers
{
    public class GoodsController : Controller
    {
        private FinalSE db = new FinalSE();

        // GET: Goods
        public ActionResult Index()
        {
            return View(db.Goods.ToList());
        }

        // GET: Goods/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Good good = db.Goods.Find(id);
            if (good == null)
            {
                return HttpNotFound();
            }
            return View(good);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplicationFinal/Views/Goods/Details.cshtml
@model WebApplicationFinal.Models.Good

@{
    ViewBag.Title = "Details";
}

@functions{
    public static string GetImageBase64String(byte[] image)
    {
        string imageBase64Data = Convert.ToBase64String(image);
        string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
        return imageDataURL;
    }
}

<h2>Details</h2>

<div>
    <h4>Good</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <p>Product name</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GName)
        </dd>

        <dt>
            <p>Manufacture</p>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacture)
        </dd>

        <dt>
            <p>Price</p>
        </dt>

        <dd>
            <p>@Model.SellingPrice.Value.ToString("n0") VND</p>
        </dd>

        <dt>
            <p>Photo</p>
        </dt>

        <dd>
            <img src="@GetImageBase64String(Model.GPhoto)" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplicationFinal/Views/Goods/Index.cshtml
@model IEnumerable<WebApplicationFinal.Models.Good>
@{
    ViewData["Title"] = "Index";
}
@functions{
    public static string GetImageBase64String(byte[] image)
    {
        string imageBase64Data = Convert.ToBase64String(image);
        string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
        return imageDataURL;
    }
}
<h2 class="text-center">Goods List</h2>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3" style="border: 2px solid black">
                <div style="text-align: center;">
                    <h3>@item.GName</h3>
                </div>

                <div class="row" style="border-top:2px solid maroon">
                    <a asp-action="Details" asp-route-id="@item.GID">
                        <div class="col-md-12 text-center">
                            <img src="@GetImageBase64String(item.GPhoto)" width="150px" height="150px" />
                        </div>
                    </a>
                </div>

                <div class="row" style="border-top:2px solid maroon">
                    <div class="col-md-8" style="font-size:18px;">
                        <b>@(item.SellingPrice.Value.ToString("n0")) VND</b>
                    </div>
                    <div class="col-md-4" style="font-size:18px;">
                        @Html.ActionLink("Details", "Details", new { id = item.GID }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Purchase", "Create", "GoodOrders", new { id = item.GID }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>